AllCops:
  Exclude:
  - bin/*
  - config/**/*
  - db/**/*
  - spec/**/*
Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 16

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/ClassAndModuleChildren:
  SupportedStyles:
    - nested
    - compact
